### ISSUE TITLE
Superpoint and lightglue models?

### ISSUE THREAD

**Issue by antithing** [AIDajiangtang/Superpoint-LightGlue-Image-Stiching#2]
Hi, thank you for this code! Can you please upload and share the models needed to run it successfully?

**Comment by AIDajiangtang** [comment]
I have uploaded it, under the Pretrained Models folder

**Comment by antithing** [comment]
Thank you! I am getting the following compile error:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: __cdecl SuperPoint::SuperPoint(void)" (__imp_??0SuperPoint@@QEAA@XZ) referenced in function main	cppDemo	D:\tracking_2022\deepfeatures\DeepLearning-based-Feature-extraction-and-matching-main\built\cppDemo.obj	1	
```

**Comment by AIDajiangtang** [comment]
Hi,


please make sure feature_matcher.lib file exist,and set to cppDemo peoject correctly. see the pic below.









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AIDajiangtang/DeepLearning-based-Feature-extraction-and-matching"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月13日(星期四) 下午2:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AIDajiangtang/DeepLearning-based-Feature-extraction-and-matching] Superpoint and lightglue models? (Issue #2)





 
Thank you! I am getting the following compile error:
 Severity	Code	Description	Project	File	Line	Suppression State Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: __cdecl SuperPoint::SuperPoint(void)" (__imp_??0SuperPoint@@***@***.***) referenced in function main	cppDemo	D:\tracking_2022\deepfeatures\DeepLearning-based-Feature-extraction-and-matching-main\built\cppDemo.obj	1

**Comment by antithing** [comment]
Hi, thank you for getting back to me. It exists (builds successfully) and is linked correctly in the cppDemo project.

**Comment by AIDajiangtang** [comment]
Hi,


please make sure feature_matcher project&nbsp; is compiled to Release x64, because in release mode,it will define a const&nbsp;definitions:FEATURE_MATCHER_EXPORTS







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AIDajiangtang/DeepLearning-based-Feature-extraction-and-matching"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月13日(星期四) 下午2:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AIDajiangtang/DeepLearning-based-Feature-extraction-and-matching] Superpoint and lightglue models? (Issue #2)





 
Thank you! I am getting the following compile error:
 Severity	Code	Description	Project	File	Line	Suppression State Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: __cdecl SuperPoint::SuperPoint(void)" (__imp_??0SuperPoint@@***@***.***) referenced in function main	cppDemo	D:\tracking_2022\deepfeatures\DeepLearning-based-Feature-extraction-and-matching-main\built\cppDemo.obj	1

**Comment by antithing** [comment]
Thanks! Actually removing the `FEATURE_MATCHER_EXPORTS` from the header files worked for me. However I am now getting runtime errors:
```

Load model from D:/tracking_2022/deepfeatures/DeepLearning-based-Feature-extraction-and-matching-main/built/Release/superpoint.onnx failed:
```

I have hardcoded the file paths in superpoint.cpp and lightglue.cpp, so it seems like a problem with the model itself.

I am on Windows, visual studio 2022, onnxruntime 1.12.0

**Comment by AIDajiangtang** [comment]
what is the error message?
here I tried onnxruntime1.15.1,it is ok.you can try it



---Original---
From: ***@***.***&gt;
Date: Thu, Jul 13, 2023 16:52 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re:[AIDajiangtang/DeepLearning-based-Feature-extraction-and-matching] Superpointand lightglue models? (Issue #2)




 
Thanks! Actually removing the FEATURE_MATCHER_EXPORTS from the header files worked for me. However I am now getting runtime errors:
  Load model from D:/tracking_2022/deepfeatures/DeepLearning-based-Feature-extraction-and-matching-main/built/Release/superpoint.onnx failed:  
I have hardcoded the file paths in superpoint.cpp and lightglue.cpp, so it seems like a problem with the model itself.
 
I am on Windows, visual studio 2022, onnxruntime 1.12.0

**Comment by AIDajiangtang** [comment]
please make sure onnxruntime.dll is in the output folder



---Original---
From: ***@***.***&gt;
Date: Thu, Jul 13, 2023 16:52 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re:[AIDajiangtang/DeepLearning-based-Feature-extraction-and-matching] Superpointand lightglue models? (Issue #2)




 
Thanks! Actually removing the FEATURE_MATCHER_EXPORTS from the header files worked for me. However I am now getting runtime errors:
  Load model from D:/tracking_2022/deepfeatures/DeepLearning-based-Feature-extraction-and-matching-main/built/Release/superpoint.onnx failed:  
I have hardcoded the file paths in superpoint.cpp and lightglue.cpp, so it seems like a problem with the model itself.
 
I am on Windows, visual studio 2022, onnxruntime 1.12.0

**Comment by antithing** [comment]
AH of course! Sorry for the stupid question. :) It is working now. Thank you!
