### ISSUE TITLE
Cuda. 

### ISSUE THREAD

**Issue by antithing** [AIDajiangtang/Superpoint-LightGlue-Image-Stiching#5]
Hi, thanks for making this project available.
Does the onnx runtime use cuda? What is the inference time?

**Comment by AIDajiangtang** [comment]
> Hi, thanks for making this project available. Does the onnx runtime use cuda? What is the inference time?

I am using the onnxrutime cpu version now, and the reasoning time is acceptable.

as I have integrated them into the OpenCV stitching pipeline. The Superpoint feature extraction time and Lighglue feature matching time are similar to traditional algorithms, but because the features they extract are more robust, Therefore, the subsequent calculation of the transformation matrix in the OpenCV stitching pipeline becomes faster, so, on the whole, it is faster than the traditional stitching algorithm.

You can also use the onnxruntime gpu version, but I'm not sure if it will be greatly improved, because the two deep learning models themselves are not very big, and data communication between gpu and cpu may also consume time.

**Comment by antithing** [comment]
Understood. Thank you for your reply.
